name: furnitureapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Core dependencies
  curved_navigation_bar: ^1.0.6
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.0.0
  # flutter_unity_widget: ^4.0.0
  model_viewer_plus: ^1.9.0
  flutter_3d_controller: ^2.0.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  api_cache_manager: ^1.0.2
  ar_flutter_plugin: ^0.7.3
  arkit_plugin: ^1.1.0


  # Flutter Localization SDK
  flutter_localizations:
    sdk: flutter

  # State management and others
  provider: ^6.0.0
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  sqflite_common_ffi: ^2.3.3+1
  flutter_stripe: ^11.2.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  vector_math: ^2.1.4
  sign_in_with_apple: ^6.1.4
  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images_3d/
    - assets/detail/Review.json
    - assets/detail/ReviewAndFeedback.json
    - assets/detail/AdminProduct.json
    - assets/detail/WaitingForDelivery.json
    - assets/detail/WaitForConfirmation.json
    - assets/detail/WriteAReview.json
    - assets/detail/Evaluate.json
    - assets/detail/OrderInformation.json
    - assets/detail/user.json
    - assets/detail/vn_only_simplified_json_generated_data_vn_units.json
