name: furnitureapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  curved_navigation_bar: ^1.0.6
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  
  # Thêm các dependencies cho model 3D
  webview_flutter: ^4.4.4  # Để hiển thị model Sketchfab
  model_viewer_plus: ^1.7.0  # Hỗ trợ xem model 3D
  url_launcher: ^6.2.5  # Để mở URL ngoài
  
  flutter:
    sdk: flutter

  # Các dependencies hiện có
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  api_cache_manager: ^1.0.2

  #sdk language
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.19.0
  shared_preferences: ^2.0.15

  sqflite_common_ffi: ^2.3.3+1
  flutter_stripe: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/detail/Review.json
    - assets/detail/ReviewAndFeedback.json
    - assets/detail/AdminProduct.json
    - assets/detail/WaitingForDelivery.json
    - assets/detail/WaitForConfirmation.json
    - assets/detail/Evaluate.json
    - assets/detail/user.json
    - assets/detail/vn_only_simplified_json_generated_data_vn_units.json

