name: furnitureapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  curved_navigation_bar: ^1.0.6 # Latest version
  
  flutter:
    sdk: flutter

  # Các dependencies khác nằm ngoài phần flutter

  http: ^1.2.2
  cupertino_icons: ^1.0.8
  api_cache_manager: ^1.0.2

  #sdk language
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.19.0
  shared_preferences: ^2.0.15

#sdk unity
<<<<<<< HEAD
  # flutter_unity_widget: ^2022.2.1
=======
>>>>>>> cc5590e2254b05421a37b5568f0b350cec073369

  sqflite_common_ffi: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/detail/product.json
    - assets/detail/Review.json
