name: furnitureapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  curved_navigation_bar: ^1.0.6 # Latest version
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.0.0
  

  flutter:
    sdk: flutter

  # Các dependencies khác nằm ngoài phần flutter

  http: ^1.2.2
  cupertino_icons: ^1.0.8
  api_cache_manager: ^1.0.2

  #sdk language
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.19.0
  shared_preferences: ^2.0.15

  #sdk unity
  # flutter_unity_widget: ^2022.2.1

  sqflite_common_ffi: ^2.3.3+1
  flutter_stripe: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/detail/Review.json
    - assets/detail/ReviewAndFeedback.json
    - assets/detail/AdminProduct.json
    - assets/detail/WaitingForDelivery.json
    - assets/detail/WaitForConfirmation.json
    - assets/detail/WriteAReview.json
    - assets/detail/Evaluate.json
    - assets/detail/OrderInformation.json
    - assets/detail/user.json
    - assets/detail/vn_only_simplified_json_generated_data_vn_units.json

